/* Copyright (C) 2015-2019, Wazuh Inc.
 * Copyright (C) 2009 Trend Micro Inc.
 * All rights reserved.
 *
 * This program is a free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public
 * License (version 2) as published by the FSF - Free Software
 * Foundation.
 */

#include "shared.h"
#include "sec.h"
#include "external/cJSON/cJSON.h"

/** Prototypes **/

/* b64 function prototypes */
char *decode_base64(const char *src);
char *encode_base64(int size, char *src);

/* Read any input from the user (stdin) */
char *read_from_user(void);

/* Add or remove an agent */
int add_agent(int json_output, int no_limit);
int remove_agent(int json_output);

/* Extract or import a key */
int k_extract(const char *cmdextract, int json_output);
int k_import(const char *cmdimport);
int k_bulkload(const char *cmdbulk);

/* Validation functions */
int OS_IsValidName(const char *u_name);
int OS_IsValidID(const char *id);
int IDExist(const char *id, int discard_removed);
int NameExist(const char *u_name);
char *IPExist(const char *u_ip);
char *getFullnameById(const char *id);
int OS_AddNewAgent(keystore *keys, const char *id, const char *name, const char *ip, const char *key);
int OS_RemoveAgent(const char *id);
double OS_AgentAntiquity(const char *name, const char *ip);
double OS_AgentAntiquity_ID(const char *id);
void OS_BackupAgentInfo(const char *id, const char *name, const char *ip);
void OS_BackupAgentInfo_ID(const char *id);
char* OS_CreateBackupDir(const char *id, const char *name, const char *ip, time_t now);
void OS_AddAgentTimestamp(const char *id, const char *name, const char *ip, time_t now);
void OS_RemoveAgentTimestamp(const char *id);
void OS_RemoveAgentGroup(const char *id);
void FormatID(char *id);

/* Load gid and uid.
 * Call before OS_BackupAgentInfo(), OS_BackupAgentInfo_ID() or OS_CreateBackupDir().
 * Should be called before chroot().
 * Returns 0 on success or -1 on failure.
 */
int OS_LoadUid();

/* Print available agents */
int print_agents(int print_status, int active_only, int inactive_only, int csv_output, cJSON *json_output);
int list_agents(int cmdlist);

/* Clear a line */
char *chomp(char *str);

/* Checks if the agent limit has been reached */
int limitReached();

/* Shared variables */
extern time_t time1;
extern time_t time2;
extern time_t time3;
extern long int rand1;
extern long int rand2;
extern fpos_t fp_pos;
extern char shost[];

/* Internal defines */
#define USER_SIZE       514
#define FILE_SIZE       257
#define STR_SIZE        66

/* Internal strings */
#define QUIT                "\\q"
#define AGENT_FILE_DELIMS   ","

/* Print agents */
#define PRINT_AVAILABLE     "\n현재 등록되어 있는 에이전트들: \n"
#define PRINT_AGENT         "   ID: %s, 이름: %s, IP: %s\n"
#define PRINT_AGENT_STATUS  "   ID: %s, 이름: %s, IP: %s, %s\n"

/* Add new agent */
#define ADD_NEW         "\n- 새로운 에이전트 추가"\
                        " ('\\q'를 누를 시 메인 메뉴로 돌아갑니다.)\n"\
                        "  다음의 사항들을 입력하세요:\n"
#define ADD_NAME        "   * 새로운 에이전트의 이름: "
#define ADD_IP          "   * 새로운 에이전트의 IP주소: "
#define ADD_ID          "   * 새로운 에이전트의 ID[%s]: "
#define AGENT_INFO      "에이전트 정보:\n   ID:%s\n   이름:%s\n   " \
                        "IP 주소:%s\n\n"
#define ADD_CONFIRM     "추가하시겠습니까?(y/n): "
#define AGENT_ADD       "ID %s 에이전트가 추가되었습니다.\n"
#define ADDED           "추가되었습니다.\n"
#define ADD_NOT         "추가되지 않았습니다..\n"
#define PRESS_ENTER     "** 메인메뉴로 돌아가기 위해서 엔터를 누르세요.\n"

/* Add errors */
#define ADD_ERROR_ID    "\n** ID '%s' 는 이미 존재하는 ID입니다. ID는 중복되지 않아야합니다.\n\n"
#define ADD_ERROR_NAME  "\n** 이름 '%s' 는 이미 존재하는 이름입니다. 새로운 이름을 입력해주세요.\n\n"
#define IP_ERROR        "\n** 유효하지 않은 IP '%s' 입니다. 유효한 IP를 입력해주세요.\n\n"
#define IP_DUP_ERROR    "\n** 중복되는 IP '%s' 입니다. 고유한 IP주소를 입력해주세요.\n\n"
#define NO_AGENT        "\n** 등록된 에이전트가 없습니다. 먼저, 새로운 에이전트를 추가해주세요.\n"
#define NO_ID           "\n** 주어진 ID '%s' 는 존재하지 않는 ID입니다.\n"
#define NO_KEY          "\n** 유효하지 않는 인증키입니다. 다시 입력해주세요. \n"
#define INVALID_ID      "\n** 주어진 ID '%s'는 유효하지 않는 ID입니다. ID는 최대 8자리의 숫자여야 합니다.\n\n"
#define INVALID_NAME    "\n** 주어진 이름 '%s'는 유효하지 않는 이름입니다. 이름은 최소 2글자에서 최대 32글자의 영문이어야 합니다.\n\n"
#define NO_DEFAULT      "\n** 기본 ID를 얻지 못했습니다. ID의 개수가 최대 수('%d')를 초과했습니다. 최대 에이전트의 개수를 추가해주시거나 에이전트를 제거해주세요.\n\n"
#define SYNTAX_ERROR    "\n** %s 파일에서 문법에러가 발생했습니다.\n\n"

/* Remove agent */
#define REMOVE_ID       "Provide the ID of the agent to be removed (or '\\q' to quit): "
#define REMOVE_CONFIRM  "Confirm deleting it?(y/n): "
#define REMOVE_DONE     "Agent '%s' removed.\n"
#define REMOVE_NOT      "Not removing.\n"

/* Import agent */
#define IMPORT_KEY      "\n* Provide the Key generated by the server.\n" \
                        "* The best approach is to cut and paste it.\n" \
                        "*** OBS: Do not include spaces or new lines.\n\n" \
                        "Paste it here (or '\\q' to quit): "

/* Extract key */
#define EXTRACT_KEY     "Provide the ID of the agent to extract " \
                        "the key (or '\\q' to quit): "
#define EXTRACT_MSG     "\nAgent key information for '%s' is: \n%s\n"


/* Common errors */
#define ERROR_KEYS      "Unable to handle keys file. Exiting.\n"
#define EXTRACT_ERROR   "Unable to extract agent key.\n"
#define INPUT_LARGE     ARGV0 ": Input too large. Not adding it.\n"
#define EXIT            ARGV0 ": Exiting.\n"

#define BANNER          "\n****************************************" \
                        "\n* %s %s Agent manager.%.*s*" \
                        "\n* The following options are available: *" \
                        "\n****************************************\n"

#define BANNER_OPT      "   (A)dd an agent (A).\n" \
                        "   (E)xtract key for an agent (E).\n" \
                        "   (L)ist already added agents (L).\n" \
                        "   (R)emove an agent (R).\n" \
                        "   (Q)uit.\n" \
                        "Choose your action: A,E,L,R or Q: "

#define BANNER_CLIENT   "   (I)mport key from the server (I).\n" \
                        "   (Q)uit.\n" \
                        "Choose your action: I or Q: "
